services:
  app:
    build:
      context: .
      target: ${GO_ENV}
    container_name: go-blog-app
    environment:
      PORT: ${PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    env_file:
      - ./.env
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - go-blog-network
    volumes:
      - .:/app

  caddy:
    image: caddy
    container_name: go-blog-caddy
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # Mount Caddyfile
      - caddy-data:/data  # For SSL certificates
      - caddy-config:/config  # For Caddy configuration
    networks:
      - go-blog-network

  postgres:
    image: postgres:bookworm
    container_name: go-blog-db
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [CMD-SHELL, "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/posgresql/data
    networks:
      - go-blog-network

  migrate:
    image: migrate/migrate
    container_name: go-blog-migrate
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - go-blog-network
    volumes:
      - ./repository/migrations/:/migrations
    command: ["-path", "/migrations/", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@go-blog-db/${POSTGRES_DB}?sslmode=disable", "up"]

volumes:
  pg-data:
  caddy-config:
  caddy-data:

networks:
  go-blog-network: